language: bash
os: linux
dist: xenial
sudo: enabled
env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8
    - SNAPCRAFT_HAS_TTY: no
    - SNAPCRAFT_ENABLE_SILENT_REPORT: yes
    - PATH: "/snap/bin:$PATH"

addons:
  snaps:
  - name: core
  - name: lxd
  - name: snapcraft
    channel: beta/lxd
    classic: true
  - name: transfer
  - name: http
before_script:
  # Avoid conflicts with socket and bridges.
  - sudo apt autoremove --purge --yes lxd lxd-client
  - sudo -E lxd waitready
  - sudo -E lxd init --auto
script:
  - sudo -E snapcraft --use-lxd
  - cp *.snap "$(echo "$TRAVIS_REPO_SLUG" | sed -e 's|.*/\(.*\)|\1|')-pr$TRAVIS_PULL_REQUEST.snap"
after_success:
  - timeout 180 transfer "$(echo "$TRAVIS_REPO_SLUG" | sed -e 's|.*/\(.*\)|\1|')-pr$TRAVIS_PULL_REQUEST.snap"
after_failure:
  - journalctl -u snapd
  - http https://api.snapcraft.io/v2/snaps/info/core architecture==amd64 Snap-Device-Series:16
