name: 'vagrant'
version: '2.1.5'
summary: A tool for building and distributing development environments
description: |
  Vagrant provides the same, easy workflow regardless of your role as
  a developer, operator, or designer. It leverages a declarative
  configuration file which describes all your software requirements,
  packages, operating system configuration, users, and more.

grade: devel
confinement: classic

apps:
  vagrant:
    environment:
      RUBYLIB: $SNAP/usr/lib/ruby/2.5.1:$SNAP/usr/lib/x86_64-linux-gnu/ruby/2.5.1
      GEM_HOME: $SNAP/gems
      GEM_PATH: $SNAP
    command: ruby $SNAP/bin/vagrant

parts:
  vagrant:
    plugin: nil
    source: 'https://github.com/hashicorp/vagrant/archive/v$SNAPCRAFT_PROJECT_VERSION.tar.gz'
    build: gem build vagrant.gemspec
    install: gem install vagrant-*.gem -i $SNAPCRAFT_PART_INSTALL.rb
    build-packages: [gcc, libc6-dev, make, ruby-dev]
    stage-packages: [ruby]
